name: cdec_maps
channels:
  - cadwr-dms
  - conda-forge
dependencies:
  - python
  - pip
  #- ipykernel
  - pyarrow
  - pandas
  - dask
  #- numba
  - aiohttp
  - requests
  - decorator
  - lxml
  - html5lib
  - bs4
  - cartopy
  - geopandas
  - holoviews
  - hvplot
  #- matplotlib
  - bokeh
  - geoviews
  #- spatialpandas
  - panel
  - diskcache
  - tqdm
  - pip:
    - git+https://github.com/CADWRDeltaModeling/vtools3
    - git+https://github.com/CADWRDeltaModeling/dvue